FROM ubuntu:xenial

## Install prerequisites
  RUN apt-get update && apt-get install -y nginx

## Copy NGINX Configuration
  COPY config/http/nginx.conf /etc/nginx/nginx.conf

## Copy the static contents
  COPY html /usr/share/nginx/html

## Start NGINX
  CMD service nginx start
