# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x
    
      - name: Setup Deploy
        run: deno install -Arf jsr:@deno/deployctl

      - name: Deploy
        run: deployctl deploy --project=jclerck https://jsr.io/@std/http/1.0.7/file_server.ts
